name: flutter_text
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
  - family: DancingScript
    fonts:
    - asset: assets/dancing_script.ttf

  uses-material-design: true